server:
  port:8081
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/NewsService
    password:
    username:
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  application:
    name: NEWS-SERVICE
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
debug: true

